In [0]:
# -*- coding:utf-8

In [0]:
import numpy as np

In [0]:
dim = 3

In [0]:
a = [[0,0,0],[1,0,0],[1,0,1],[1,1,0]]
#print(a1)

In [0]:
b = [[0,0,1],[0,1,1],[0,1,0],[1,1,1]]
#数据定义

In [0]:
a_num = len(a)
b_num = len(b)

In [92]:
a_array=[]
for i in range(a_num):
  a[i].append(1)
  tmp_narry = np.array(a[i])
  print(tmp_narr)
  a_array.append(tmp_narry)

[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]


In [93]:
b_array=[]
for i in range(b_num):
  b[i].append(1)
  b[i] = np.dot(b[i],-1)
  tmp_narry = np.array(b[i])
  print(tmp_narr)
  b_array.append(tmp_narry)

[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]


In [94]:
print(b_array)

[array([ 0,  0, -1, -1]), array([ 0, -1, -1, -1]), array([ 0, -1,  0, -1]), array([-1, -1, -1, -1])]


In [110]:
print(a_array,"\n",b_array)
array = a_array+b_array
print(array)
w = np.zeros(dim+1).T
print(w)
C = 0.5
#初始参数
w_num = 0
iter_num = 1
while True:
  flag = False
  print("第%d轮迭代:"%iter_num)
  for arr in array:
    res = np.dot(arr,w)
    print(arr,"*",w,end='')
    if res<=0:
      print("="+str(res)+"<=0",end='   ')
      print("故w("+str(w_num+1)+")=w("+str(w_num)+")+",arr)
      w = w + np.dot(arr,C)
      flag=True
    else:
      print("="+str(res)+">0",end='   ')
      print("故w("+str(w_num+1)+")=w("+str(w_num)+")")
    w_num = w_num + 1
  iter_num = iter_num + 1
  if flag==False or iter_num>999:
    break
print("w:",w)
print("d(x)="+str(w[0])+"*X1+"+str(w[1])+"*X2+"+str(w[2])+"*X3+"+str(w[3]))

[array([0, 0, 0, 1]), array([1, 0, 0, 1]), array([1, 0, 1, 1]), array([1, 1, 0, 1])] 
 [array([ 0,  0, -1, -1]), array([ 0, -1, -1, -1]), array([ 0, -1,  0, -1]), array([-1, -1, -1, -1])]
[array([0, 0, 0, 1]), array([1, 0, 0, 1]), array([1, 0, 1, 1]), array([1, 1, 0, 1]), array([ 0,  0, -1, -1]), array([ 0, -1, -1, -1]), array([ 0, -1,  0, -1]), array([-1, -1, -1, -1])]
[0. 0. 0. 0.]
第1轮迭代:
[0 0 0 1] * [0. 0. 0. 0.]=0.0<=0   故w(1)=w(0)+ [0 0 0 1]
[1 0 0 1] * [0.  0.  0.  0.5]=0.5>0   故w(2)=w(1)
[1 0 1 1] * [0.  0.  0.  0.5]=0.5>0   故w(3)=w(2)
[1 1 0 1] * [0.  0.  0.  0.5]=0.5>0   故w(4)=w(3)
[ 0  0 -1 -1] * [0.  0.  0.  0.5]=-0.5<=0   故w(5)=w(4)+ [ 0  0 -1 -1]
[ 0 -1 -1 -1] * [ 0.   0.  -0.5  0. ]=0.5>0   故w(6)=w(5)
[ 0 -1  0 -1] * [ 0.   0.  -0.5  0. ]=0.0<=0   故w(7)=w(6)+ [ 0 -1  0 -1]
[-1 -1 -1 -1] * [ 0.  -0.5 -0.5 -0.5]=1.5>0   故w(8)=w(7)
第2轮迭代:
[0 0 0 1] * [ 0.  -0.5 -0.5 -0.5]=-0.5<=0   故w(9)=w(8)+ [0 0 0 1]
[1 0 0 1] * [ 0.  -0.5 -0.5  0. ]=0.0<=0   故w(10)=w(9)+ [1 0 0 1]
[1 0 1